/* Generated By:JJTree: Do not edit this line. ASTAssignmentBoolean.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=intepreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTAssignmentBoolean extends SimpleNode {
  public ASTAssignmentBoolean(int id) {
    super(id);
  }

  public ASTAssignmentBoolean(Jlang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JlangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=89bc5c8628820143c58cfcd773d5b943 (do not edit this line) */
