/* Generated By:JJTree: Do not edit this line. ASTAssignmentString.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=intepreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTAssignmentString extends SimpleNode {
  public ASTAssignmentString(int id) {
    super(id);
  }

  public ASTAssignmentString(Jlang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JlangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=59e08fd992c54f6d7e7274b930a68b1c (do not edit this line) */
