/* Generated By:JJTree: Do not edit this line. ASTComparisonLessThan.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=intepreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTComparisonLessThan extends SimpleNode {
  public ASTComparisonLessThan(int id) {
    super(id);
  }

  public ASTComparisonLessThan(Jlang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JlangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d30b854587eb719b3789985aca293eba (do not edit this line) */
