/* Generated By:JJTree: Do not edit this line. ASTComparisonLessThanOrEqualTo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=intepreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTComparisonLessThanOrEqualTo extends SimpleNode {
  public ASTComparisonLessThanOrEqualTo(int id) {
    super(id);
  }

  public ASTComparisonLessThanOrEqualTo(Jlang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JlangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=959368bad8e9acd08412dc9a9e57bdf3 (do not edit this line) */
