/* Generated By:JJTree: Do not edit this line. ASTComparisonGreatorThanOrEqualTo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=intepreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTComparisonGreatorThanOrEqualTo extends SimpleNode {
  public ASTComparisonGreatorThanOrEqualTo(int id) {
    super(id);
  }

  public ASTComparisonGreatorThanOrEqualTo(Jlang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JlangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e85be58cab2bf496c89285ea3a3a9c70 (do not edit this line) */
