/* Generated By:JJTree: Do not edit this line. ASTComparisonNotEqualTo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=intepreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTComparisonNotEqualTo extends SimpleNode {
  public ASTComparisonNotEqualTo(int id) {
    super(id);
  }

  public ASTComparisonNotEqualTo(Jlang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JlangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=241aa9bf08b366ec0193db528dbb106e (do not edit this line) */
