/* Generated By:JJTree: Do not edit this line. ASTComparisonGreatorThan.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=intepreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTComparisonGreatorThan extends SimpleNode {
  public ASTComparisonGreatorThan(int id) {
    super(id);
  }

  public ASTComparisonGreatorThan(Jlang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JlangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3ce6a472399bfbdb3a480aeb9d28a864 (do not edit this line) */
