/* Generated By:JJTree: Do not edit this line. ASTUnaryMinusOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=intepreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTUnaryMinusOperator extends SimpleNode {
  public ASTUnaryMinusOperator(int id) {
    super(id);
  }

  public ASTUnaryMinusOperator(Jlang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JlangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8bc251c66625c989e4e9560298edc89a (do not edit this line) */
