/* Generated By:JJTree: Do not edit this line. ASTUnaryPlusOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=intepreter.BaseASTNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser.ast;

public
class ASTUnaryPlusOperator extends SimpleNode {
  public ASTUnaryPlusOperator(int id) {
    super(id);
  }

  public ASTUnaryPlusOperator(Jlang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JlangVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1f517cd5ead61b193c3ea31ffad2705f (do not edit this line) */
