/* Generated By:JavaCC: Do not edit this line. JlangTreeConstants.java Version 5.0 */
package parser.ast;

public interface JlangTreeConstants
{
  public int JJTCODE = 0;
  public int JJTSTATEMENT = 1;
  public int JJTBLOCK = 2;
  public int JJTPARMLIST = 3;
  public int JJTFNBODY = 4;
  public int JJTFNDEF = 5;
  public int JJTRETURNEXPRESSION = 6;
  public int JJTVOID = 7;
  public int JJTASSIGNMENT = 8;
  public int JJTASSIGNMENTINTEGER = 9;
  public int JJTASSIGNMENTSTRING = 10;
  public int JJTASSIGNMENTFLOAT = 11;
  public int JJTASSIGNMENTBOOLEAN = 12;
  public int JJTIFSTATEMENT = 13;
  public int JJTFORLOOP = 14;
  public int JJTWHILELOOP = 15;
  public int JJTSWITCHSTATEMENT = 16;
  public int JJTWRITE = 17;
  public int JJTCALL = 18;
  public int JJTARGLIST = 19;
  public int JJTOREXPRESSION = 20;
  public int JJTANDEXPRESSION = 21;
  public int JJTCOMPARISONEQUAL = 22;
  public int JJTCOMPARISONNOTEQUALTO = 23;
  public int JJTCOMPARISONGREATORTHANOREQUALTO = 24;
  public int JJTCOMPARISONLESSTHANOREQUALTO = 25;
  public int JJTCOMPARISONGREATORTHAN = 26;
  public int JJTCOMPARISONLESSTHAN = 27;
  public int JJTADDOPERATOR = 28;
  public int JJTSUBTRACTOPERATOR = 29;
  public int JJTTIMESOPERATOR = 30;
  public int JJTDIVIDEOPERATOR = 31;
  public int JJTUNARYNOTOPERATOR = 32;
  public int JJTUNARYPLUSOPERATOR = 33;
  public int JJTUNARYMINUSOPERATOR = 34;
  public int JJTFNINVOKE = 35;
  public int JJTIDENTIFIER = 36;
  public int JJTDEREFERENCE = 37;
  public int JJTCHARACTER = 38;
  public int JJTINTEGER = 39;
  public int JJTRATIONAL = 40;
  public int JJTTRUE = 41;
  public int JJTFALSE = 42;


  public String[] jjtNodeName = {
    "Code",
    "Statement",
    "Block",
    "Parmlist",
    "FnBody",
    "FnDef",
    "ReturnExpression",
    "void",
    "Assignment",
    "AssignmentInteger",
    "AssignmentString",
    "AssignmentFloat",
    "AssignmentBoolean",
    "IfStatement",
    "ForLoop",
    "WhileLoop",
    "SwitchStatement",
    "Write",
    "Call",
    "ArgList",
    "OrExpression",
    "AndExpression",
    "ComparisonEqual",
    "ComparisonNotEqualTo",
    "ComparisonGreatorThanOrEqualTo",
    "ComparisonLessThanOrEqualTo",
    "ComparisonGreatorThan",
    "ComparisonLessThan",
    "AddOperator",
    "SubtractOperator",
    "TimesOperator",
    "DivideOperator",
    "UnaryNotOperator",
    "UnaryPlusOperator",
    "UnaryMinusOperator",
    "FnInvoke",
    "Identifier",
    "Dereference",
    "Character",
    "Integer",
    "Rational",
    "True",
    "False",
  };
}
/* JavaCC - OriginalChecksum=13b9d817f200aaa0aee7804aab6b74d4 (do not edit this line) */
