/* Generated By:JJTree&JavaCC: Do not edit this line. JlangConstants.java */
package parser.ast;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JlangConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int IF = 8;
  /** RegularExpression Id. */
  int ELSEIF = 9;
  /** RegularExpression Id. */
  int ELSE = 10;
  /** RegularExpression Id. */
  int FOR = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int SWITCH = 13;
  /** RegularExpression Id. */
  int CASE = 14;
  /** RegularExpression Id. */
  int SWITCHDEFAULT = 15;
  /** RegularExpression Id. */
  int BREAK = 16;
  /** RegularExpression Id. */
  int WRITE = 17;
  /** RegularExpression Id. */
  int FN = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int NOT = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int INT = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int FLOAT = 27;
  /** RegularExpression Id. */
  int BOOL = 28;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 29;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 30;
  /** RegularExpression Id. */
  int HEX_LITERAL = 31;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 32;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 33;
  /** RegularExpression Id. */
  int EXPONENT = 34;
  /** RegularExpression Id. */
  int STRING_LITERAL = 35;
  /** RegularExpression Id. */
  int IDENTIFIER = 36;
  /** RegularExpression Id. */
  int LETTER = 37;
  /** RegularExpression Id. */
  int DIGIT = 38;
  /** RegularExpression Id. */
  int LPAREN = 39;
  /** RegularExpression Id. */
  int RPAREN = 40;
  /** RegularExpression Id. */
  int LBRACE = 41;
  /** RegularExpression Id. */
  int RBRACE = 42;
  /** RegularExpression Id. */
  int LBRACKET = 43;
  /** RegularExpression Id. */
  int RBRACKET = 44;
  /** RegularExpression Id. */
  int SEMICOLON = 45;
  /** RegularExpression Id. */
  int COMMA = 46;
  /** RegularExpression Id. */
  int DOT = 47;
  /** RegularExpression Id. */
  int ASSIGN = 48;
  /** RegularExpression Id. */
  int PEQ = 49;
  /** RegularExpression Id. */
  int MEQ = 50;
  /** RegularExpression Id. */
  int UEQ = 51;
  /** RegularExpression Id. */
  int EQ = 52;
  /** RegularExpression Id. */
  int GT = 53;
  /** RegularExpression Id. */
  int LT = 54;
  /** RegularExpression Id. */
  int LE = 55;
  /** RegularExpression Id. */
  int GE = 56;
  /** RegularExpression Id. */
  int NE = 57;
  /** RegularExpression Id. */
  int PLUS = 58;
  /** RegularExpression Id. */
  int SUBT = 59;
  /** RegularExpression Id. */
  int STAR = 60;
  /** RegularExpression Id. */
  int SLASH = 61;
  /** RegularExpression Id. */
  int REM = 62;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"IF\"",
    "\"ELSEIF\"",
    "\"ELSE\"",
    "\"FOR\"",
    "\"WHILE\"",
    "\"SWITCH\"",
    "\"CASE\"",
    "\"DEFAULT\"",
    "\"BREAK\"",
    "\"WRITE\"",
    "\"FN\"",
    "\"RETURN\"",
    "\"OR\"",
    "\"AND\"",
    "\"NOT\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"INT\"",
    "\"STRING\"",
    "\"FLOAT\"",
    "\"BOOL\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"@=\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\":\"",
  };

}
